### ISSUE TITLE
ticker make all error

### ISSUE THREAD

**Issue by bornhaeusser** [jaypeeteeB/MyPHPpa#1]
/var/www/html/MyPA/ticker# make all
gcc -O -g ticker.o score.o update.o core_sql.o helper.o battle.o cleanup.o logging.o -o ticker -lmysqlclient -lcrypt -lz
/usr/bin/ld: battle.o: undefined reference to symbol 'truncf@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'ticker' failed
make: *** [ticker] Error 1

**Comment by jaypeeteeB** [comment]
I have currently no "arm" available. Did you try to add "-lm" (behind "-lz")?

**Comment by bornhaeusser** [comment]
ok thanks - went througt now
