### ISSUE TITLE
time wrong - last ticker

### ISSUE THREAD

**Issue by bornhaeusser** [jaypeeteeB/MyPHPpa#4]
the last ticker time is 5 minutes agao.
System times on server are right. Where is comming the time from?

**Comment by jaypeeteeB** [comment]
There is an utility tick_sleep which is triggered by tick.sh. It writes a 'tmp'-file whose timestamp is read by javascript code in header.php.

It has to be configured in options.php (for the javascript) and in mypa.cfg/tick.sh  for the ticker.
